# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [9]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [13]:
np.arange(10, 51, step=2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.array([[0,1,2], [3,4,5], [6,7,8]], dtype=np.int32)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

#### Create a 3x3 identity matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [22]:
np.random.rand(1)

array([0.12123283])

In [24]:
np.random.rand(4, 4)

array([[0.0389764 , 0.08908576, 0.84904958, 0.89765166],
       [0.13303799, 0.85709074, 0.75713846, 0.66858151],
       [0.67867334, 0.80774708, 0.03276513, 0.00928316],
       [0.52398623, 0.23791684, 0.87426079, 0.52168067]])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [25]:
np.random.randn(25)

array([ 0.1268783 , -0.26303484, -0.75372409,  0.29345122, -0.25825552,
        1.26860279, -1.04556853, -0.0731281 , -0.80386332, -0.73691168,
        0.21538887,  0.71841264, -0.76928816, -0.53982929,  1.61390556,
       -1.34306577,  0.74901734,  0.2872134 , -1.07836449, -0.02016159,
       -0.54808626, -1.13183336,  0.93092008,  0.95926236, -0.71607672])

In [26]:
# generate an array of 50 random numbers
np.random.randn(50)

array([ 3.99758229e-01, -1.24874133e-01,  1.39447034e+00,  1.04555839e-01,
       -1.60566213e+00,  5.36541296e-02,  2.23442605e+00,  1.21566465e+00,
       -4.13462677e-01,  3.54738327e-01,  7.16005337e-01,  1.00134950e+00,
        6.54316473e-01, -9.40109760e-02,  1.06009398e+00,  1.04652381e-01,
       -2.42792095e-01, -7.91419867e-01, -8.55566740e-01,  2.39029883e+00,
       -8.02036066e-04, -1.83493152e+00, -1.73560098e-01, -3.29947979e-03,
       -1.55698338e+00, -1.40460176e+00, -2.67811289e-01, -2.00072768e+00,
        8.95750591e-01,  1.43839908e+00, -9.21652229e-01, -5.12028032e-01,
        1.85021522e+00, -2.61221282e-01,  6.07119809e-01, -1.21470716e+00,
        3.68244783e-01, -6.91251994e-01, -6.72284085e-01,  3.80311054e-01,
       -1.10098730e+00, -7.43150460e-03, -7.74393106e-02, -6.67710379e-01,
        5.55042691e-01, -7.53439271e-01, -2.96255235e-01, -3.38294270e-01,
        1.86819706e+00, -6.87766530e-01])

#### Create the following matrix:

In [27]:
np.arange(1, 101).reshape(10, 10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [30]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

#### Get the standard deviation of the values in mat

7.2111025509279782

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Great Job!